# Generated by Django 2.2 on 2019-05-02 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('businessman', 'phone')},
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customers',
        ),
    ]
