# Generated by Django 2.2 on 2019-07-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessman',
            name='friend_invitation_access',
            field=models.BooleanField(default=False),
        ),
    ]
