# Generated by Django 2.2 on 2019-04-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesman',
            name='address',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
