# Generated by Django 2.2 on 2019-05-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190502_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessman',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
