# Generated by Django 2.2 on 2019-04-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190419_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='instagarm_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
