# Generated by Django 2.2 on 2019-07-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190730_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessman',
            name='logo',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='media/logo'),
        ),
    ]
