# Generated by Django 2.2 on 2019-07-18 20:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_businessman_friend_invitation_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessman',
            name='friend_invitation_access',
        ),
        migrations.AddField(
            model_name='businessman',
            name='friend_invitation_access_expire',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 20, 19, 31, 928891, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
