# Generated by Django 2.2 on 2019-04-22 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190422_0742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='instagarm_id',
            new_name='instagram_id',
        ),
    ]
