# Generated by Django 2.2 on 2019-07-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190719_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessman',
            name='friend_invitation_access_expire',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
