# Generated by Django 2.2 on 2019-07-31 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_businessman_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessman',
            name='logo',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='logo'),
        ),
    ]
