# Generated by Django 2.2 on 2019-04-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_salesman_store_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesman',
            name='store_name',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
