# Generated by Django 2.2 on 2019-07-31 17:50

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190731_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessman',
            name='logo',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to=users.models.Businessman.get_upload_path),
        ),
    ]
