# Generated by Django 2.2 on 2019-04-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190414_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesman',
            name='store_name',
            field=models.CharField(max_length=1000),
        ),
    ]
