# Generated by Django 2.2 on 2019-07-18 20:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190719_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessman',
            name='friend_invitation_access_expire',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 20, 28, 59, 506615, tzinfo=utc)),
        ),
    ]
