# Generated by Django 2.2 on 2019-05-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190427_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcodes',
            name='code',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
