# Generated by Django 2.2 on 2019-07-18 20:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190719_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessman',
            name='friend_invitation_access_expire',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
