# Generated by Django 2.2 on 2019-04-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190414_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesman',
            name='bot_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesman',
            name='instagram_access',
            field=models.BooleanField(default=False),
        ),
    ]
