# Generated by Django 2.2 on 2019-08-02 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190731_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessmanRefreshTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generate_at', models.DateTimeField(auto_now_add=True)),
                ('expire_at', models.DateTimeField()),
                ('ip', models.GenericIPAddressField()),
                ('username', models.CharField(max_length=40)),
                ('businessman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
