# Generated by Django 2.2 on 2019-04-15 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190415_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesman',
            old_name='store_name',
            new_name='business_name',
        ),
    ]
