# Generated by Django 2.2 on 2019-08-02 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_businessmanrefreshtokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessmanrefreshtokens',
            name='businessman',
        ),
    ]
