# Generated by Django 2.2 on 2019-04-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190415_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesman',
            name='bot_access_expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesman',
            name='instagram_access_expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
