# Generated by Django 2.2 on 2019-08-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_businessmanrefreshtokens_businessman'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessman',
            name='bot_access_expire',
        ),
        migrations.RemoveField(
            model_name='businessman',
            name='friend_invitation_access_expire',
        ),
        migrations.RemoveField(
            model_name='businessman',
            name='instagram_access_expire',
        ),
        migrations.AddField(
            model_name='businessman',
            name='instagram_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='businessman',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
