# Generated by Django 2.2 on 2019-10-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190803_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessman',
            name='authorized',
            field=models.CharField(choices=[('0', 'UNAUTHORIZED'), ('1', 'PENDING'), ('2', 'AUTHORIZED')], default='0', max_length=1),
        ),
    ]
