# Generated by Django 2.2 on 2020-01-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_businessman_authorized'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessman',
            name='panel_activation_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='businessman',
            name='panel_expiration_date',
            field=models.DateTimeField(null=True),
        ),
    ]
