# Generated by Django 2.2 on 2020-04-21 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200421_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessman',
            name='business_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.BusinessCategory'),
        ),
    ]
