# Generated by Django 2.2 on 2020-08-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_customeronetimepasswords'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLoginTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.TextField()),
                ('user_agent', models.TextField()),
                ('customer_phone', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
