# Generated by Django 2.2 on 2020-08-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_customerlogintokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeronetimepasswords',
            name='send_attempts',
            field=models.IntegerField(default=1),
        ),
    ]
