# Generated by Django 2.2 on 2020-08-08 09:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20200808_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='businessmans',
            field=models.ManyToManyField(related_name='customers', related_query_name='customers', through='users.BusinessmanCustomer', to=settings.AUTH_USER_MODEL),
        ),
    ]
