# Generated by Django 2.2 on 2020-08-08 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20200808_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmancustomer',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_businessmans', related_query_name='connected_businessmans', to='users.Customer'),
        ),
    ]
