# Generated by Django 2.2 on 2020-08-08 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20200808_0958'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='businessmancustomer',
            unique_together={('businessman', 'customer')},
        ),
    ]
