# Generated by Django 2.2 on 2020-08-08 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20200808_1137'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerLoginTokens',
        ),
        migrations.DeleteModel(
            name='CustomerOneTimePasswords',
        ),
    ]
