# Generated by Django 2.2 on 2020-10-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20201006_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessman',
            name='panel_duration_type',
        ),
        migrations.AddField(
            model_name='businessman',
            name='duration_type',
            field=models.CharField(choices=[('M', 'MONTHLY'), ('Y', 'YEARLY'), ('PER', 'PERMANENT')], default='M', max_length=2),
        ),
    ]
