# Generated by Django 2.2 on 2020-10-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20201006_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessman',
            name='panel_activation_date',
            field=models.DateTimeField(null=True),
        ),
    ]
