# Generated by Django 2.2 on 2020-10-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20201006_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessman',
            name='duration_type',
            field=models.CharField(choices=[('M', 'MONTHLY'), ('Y', 'YEARLY'), ('PER', 'PERMANENT')], default='M', max_length=10),
        ),
    ]
