# Generated by Django 2.2 on 2020-10-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20201006_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_phone_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
