# Generated by Django 2.2 on 2020-11-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20201108_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessman',
            name='page_id',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
