# Generated by Django 2.2 on 2020-12-21 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_businessmancustomer_joined_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessman',
            name='address',
        ),
    ]
