# Generated by Django 2.2 on 2021-05-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_remove_businessman_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcodes',
            name='used_for',
            field=models.CharField(choices=[('0', 'Phone verification'), ('2', 'Phone change')], default='0', max_length=2),
        ),
    ]
