# Generated by Django 2.2 on 2021-05-03 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20210502_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneChangeVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('new_phone', models.CharField(max_length=20)),
                ('businessman', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('new_phone_verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_change_new', related_query_name='phone_change_new', to='users.VerificationCodes')),
                ('previous_phone_verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_change_previous', related_query_name='phone_change_previous', to='users.VerificationCodes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
