# Generated by Django 2.2 on 2021-05-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_phonechangeverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessman',
            name='viewed_intro',
            field=models.BooleanField(default=False),
        ),
    ]
