# Generated by Django 2.2 on 2021-05-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_businessman_viewed_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmancustomer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
