# Generated by Django 2.2 on 2021-06-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0039_businessmancustomer_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmancustomer',
            name='joined_by',
            field=models.CharField(choices=[('0', 'By Panel'), ('1', 'Customer App'), ('2', 'Joined by invitation')],
                                   default='0', max_length=2),
        ),
    ]
