# Generated by Django 2.2 on 2019-07-30 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('festivals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='businessman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='festival',
            name='customers',
            field=models.ManyToManyField(to='users.Customer'),
        ),
        migrations.AlterUniqueTogether(
            name='festival',
            unique_together={('businessman', 'discount_code'), ('businessman', 'name')},
        ),
    ]
