# Generated by Django 2.2 on 2019-08-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0005_auto_20190801_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='messages_sent',
            field=models.BooleanField(default=False),
        ),
    ]
