# Generated by Django 2.2 on 2020-03-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0008_festival_message_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='percent_off',
            field=models.FloatField(default=0),
        ),
    ]
