# Generated by Django 2.2 on 2020-03-24 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_return_plan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('festivals', '0009_auto_20200314_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='discount',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='customer_return_plan.Discount'),
        ),
        migrations.AlterUniqueTogether(
            name='festival',
            unique_together={('businessman', 'name')},
        ),
        migrations.RemoveField(
            model_name='festival',
            name='customers',
        ),
        migrations.RemoveField(
            model_name='festival',
            name='discount_code',
        ),
        migrations.RemoveField(
            model_name='festival',
            name='flat_rate_off',
        ),
        migrations.RemoveField(
            model_name='festival',
            name='percent_off',
        ),
    ]
