# Generated by Django 2.2 on 2020-06-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0014_auto_20200415_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='mark_as_deleted_for_businessman',
            field=models.BooleanField(default=False),
        ),
    ]
