# Generated by Django 2.2 on 2020-06-06 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0015_festival_mark_as_deleted_for_businessman'),
    ]

    operations = [
        migrations.RenameField(
            model_name='festival',
            old_name='mark_as_deleted_for_businessman',
            new_name='marked_as_deleted_for_businessman',
        ),
    ]
