# Generated by Django 2.2 on 2020-06-09 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0016_auto_20200606_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festival',
            name='marked_as_deleted_for_businessman',
        ),
    ]
