# Generated by Django 2.2 on 2020-08-08 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0016_auto_20200606_1746'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='festival',
            unique_together=set(),
        ),
    ]
