# Generated by Django 2.2 on 2020-09-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20200817_1733'),
        ('festivals', '0017_auto_20200808_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='remaining_pwa_notif_customers',
            field=models.ManyToManyField(to='users.Customer'),
        ),
        migrations.AddField(
            model_name='festival',
            name='send_pwa_notif',
            field=models.BooleanField(default=False),
        ),
    ]
