# Generated by Django 2.2 on 2020-09-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0018_auto_20200923_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='remaining_pwa_notif_customers',
            field=models.ManyToManyField(blank=True, to='users.Customer'),
        ),
    ]
