# Generated by Django 2.2 on 2020-04-10 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_businessman_has_sms_panel'),
        ('customer_return_plan', '0003_auto_20200325_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='reserved_for',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Customer'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='used_for',
            field=models.CharField(choices=[('0', 'None'), ('1', 'Festival'), ('2', 'Invitation'), ('3', 'Loyalty')], default='0', max_length=2),
        ),
    ]
