# Generated by Django 2.2 on 2020-04-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_return_plan', '0005_auto_20200411_0213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='reserved_for',
        ),
        migrations.AlterField(
            model_name='discount',
            name='used_for',
            field=models.CharField(choices=[('0', 'None'), ('1', 'Festival'), ('2', 'Invitation'), ('3', 'Loyalty')], default='0', max_length=2),
        ),
    ]
