# Generated by Django 2.2 on 2020-04-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_return_plan', '0006_auto_20200412_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
