# Generated by Django 2.2 on 2020-05-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_return_plan', '0009_auto_20200415_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='purchases',
            field=models.ManyToManyField(blank=True, null=True, related_name='purchases', related_query_name='purchases', to='customerpurchase.CustomerPurchase'),
        ),
    ]
