# Generated by Django 2.2 on 2020-05-31 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customerpurchase', '0010_auto_20200415_1122'),
        ('customer_return_plan', '0010_auto_20200527_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='purchases',
        ),
        migrations.CreateModel(
            name='PurchaseDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', related_query_name='purchases', to='customer_return_plan.Discount')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', related_query_name='purchases', to='customerpurchase.CustomerPurchase')),
            ],
            options={
                'unique_together': {('purchase', 'discount')},
            },
        ),
        migrations.AddField(
            model_name='discount',
            name='connected_purchases',
            field=models.ManyToManyField(blank=True, null=True, related_name='connected_purchases', related_query_name='connected_purchases', through='customer_return_plan.PurchaseDiscount', to='customerpurchase.CustomerPurchase'),
        ),
    ]
