# Generated by Django 2.2 on 2020-06-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_return_plan', '0013_auto_20200531_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='connected_purchases',
            field=models.ManyToManyField(related_name='connected_purchases', related_query_name='connected_purchases', through='customer_return_plan.PurchaseDiscount', to='customerpurchase.CustomerPurchase'),
        ),
    ]
