# Generated by Django 2.2 on 2020-06-01 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_return_plan', '0014_auto_20200601_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasediscount',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_discount', related_query_name='purchase_discount', to='customerpurchase.CustomerPurchase'),
        ),
    ]
