# Generated by Django 2.2 on 2021-07-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('customer_return_plan', '0015_auto_20200601_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='used_for',
            field=models.CharField(choices=[('0', 'None'), ('1', 'Festival'), ('2', 'Invitation'), ('3', 'Loyalty')],
                                   default='0', max_length=2),
        ),
    ]
