# Generated by Django 2.2 on 2019-11-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20191016_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PAID', 'paid'), ('PENDING', 'pending'), ('UNPAID', 'unpaid')], default='PENDING', max_length=2),
        ),
    ]
