# Generated by Django 2.2 on 2020-01-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20191201_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.IntegerField(),
        ),
    ]
