# Generated by Django 2.2 on 2020-01-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20200124_0908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='status',
            new_name='create_status',
        ),
        migrations.AddField(
            model_name='payment',
            name='verification_status',
            field=models.IntegerField(null=True),
        ),
    ]
