# Generated by Django 2.2 on 2020-01-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20200124_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='verification_date',
            field=models.DateTimeField(null=True),
        ),
    ]
