# Generated by Django 2.2 on 2020-01-26 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0011_auto_20200124_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedPaymentOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.IntegerField()),
                ('operation_type', models.CharField(choices=[('SMS', '0'), ('ACTIVATION', '1')], default='0', max_length=2)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('is_fixed', models.BooleanField(default=False)),
                ('businessman', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='payment.Payment')),
            ],
        ),
    ]
