# Generated by Django 2.2 on 2020-10-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_panelactivationplans'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelactivationplans',
            name='durations',
            field=models.CharField(choices=[('MONTHLY', 'M'), ('YEARLY', 'Y'), ('PERMANENT', 'PER')], default='M', max_length=2),
        ),
    ]
