# Generated by Django 2.2 on 2020-10-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_panelactivationplans_durations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panelactivationplans',
            name='durations',
        ),
        migrations.AddField(
            model_name='panelactivationplans',
            name='duration_type',
            field=models.CharField(choices=[('M', 'MONTHLY'), ('Y', 'YEARLY'), ('PER', 'PERMANENT')], default='M', max_length=2),
        ),
    ]
