# Generated by Django 2.2 on 2020-10-05 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_auto_20201005_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panelactivationplans',
            name='is_permanent',
        ),
    ]
