# Generated by Django 2.2 on 2020-10-05 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_remove_panelactivationplans_is_permanent'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='panel_plan_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.PanelActivationPlans'),
        ),
    ]
