# Generated by Django 2.2 on 2020-10-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0018_auto_20201005_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelactivationplans',
            name='duration_type',
            field=models.CharField(choices=[('M', 'MONTHLY'), ('Y', 'YEARLY'), ('PER', 'PERMANENT')], default='M', max_length=10),
        ),
    ]
