# Generated by Django 2.2 on 2021-06-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payment', '0019_auto_20201006_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failedpaymentoperation',
            name='operation_type',
            field=models.CharField(choices=[('SMS', 'SMS'), ('ACTIVATION', 'WALLET')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('SMS', 'SMS'), ('ACTIVATION', 'WALLET')], default='0', max_length=10),
        ),
    ]
