# Generated by Django 2.2 on 2021-06-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payment', '0020_auto_20210620_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='call_back_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
