# Generated by Django 2.2 on 2021-06-26 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0040_auto_20210620_1957'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0022_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('amount', models.BigIntegerField()),
                ('businessman',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('customer_added', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                                     to='users.BusinessmanCustomer')),
            ],
            options={
                'db_table': 'billing',
                'ordering': ('-create_date', '-update_date'),
            },
        ),
    ]
