# Generated by Django 2.2 on 2021-07-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payment', '0024_billing_jcreate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='has_subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallet',
            name='subscription_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='subscription_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
