# Generated by Django 2.2 on 2021-07-18 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payment', '0025_auto_20210704_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('duration', models.CharField(
                    choices=[('1_MONTH', '1 ماهه'), ('2_MONTH', '3 ماهه'), ('6_MONTH', '6 ماهه'), ('1_YEAR', '1 ساله')],
                    max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_in_toman', models.PositiveIntegerField()),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='failedpaymentoperation',
            name='operation_type',
            field=models.CharField(choices=[('SMS', 'SMS'), ('WALLET', 'WALLET')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='payment',
            name='panel_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='payment.SubscriptionPlan'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('SMS', 'SMS'), ('WALLET', 'WALLET')], default='0', max_length=10),
        ),
        migrations.DeleteModel(
            name='PanelActivationPlans',
        ),
    ]
