# Generated by Django 2.2 on 2021-07-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payment', '0027_auto_20210718_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration',
            field=models.CharField(
                choices=[('1_MONTH', '1 ماهه'), ('3_MONTH', '3 ماهه'), ('6_MONTH', '6 ماهه'), ('1_YEAR', '1 ساله')],
                max_length=20),
        ),
    ]
