# Generated by Django 2.2 on 2019-11-21 20:18

import content_marketing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videofile',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to=content_marketing.models.Video.get_upload_path),
        ),
    ]
