# Generated by Django 2.2 on 2019-12-09 20:55

import content_marketing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_businessman_authorized'),
        ('content_marketing', '0002_auto_20191128_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='videofile',
            field=models.FileField(max_length=254, upload_to=content_marketing.models.Post.get_upload_path),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('customer', 'post')},
        ),
    ]
