# Generated by Django 2.2 on 2020-03-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_marketing', '0002_auto_20200308_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sms_sent',
            field=models.BooleanField(default=False),
        ),
    ]
