# Generated by Django 2.2 on 2020-01-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_marketing', '0003_auto_20191210_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
