# Generated by Django 2.2 on 2020-01-29 09:59

import content_marketing.models
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content_marketing', '0004_post_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='videofile',
            field=models.FileField(max_length=254, storage=django.core.files.storage.FileSystemStorage(base_url='/content/video/', location='C:\\Users\\Pouya\\Desktop\\programs\\python\\marketpine-backend\\..\\videos/'), upload_to=content_marketing.models.Post.get_upload_path),
        ),
        migrations.CreateModel(
            name='ContentMarketingSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_template', models.CharField(default='', max_length=260)),
                ('send_video_upload_message', models.BooleanField(default=False)),
                ('businessman', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='content_matketing_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
