# Generated by Django 2.2 on 2020-06-11 16:10

import base_app.models
import content_marketing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_marketing', '0006_auto_20200502_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mobile_thumbnail',
            field=models.ImageField(max_length=254, null=True, storage=base_app.models.PublicFileStorage(base_url='/content/video/', subdir='videos/'), upload_to=content_marketing.models.Post.get_upload_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='videofile',
            field=models.FileField(max_length=254, storage=base_app.models.PublicFileStorage(base_url='/content/video/', subdir='videos/'), upload_to=content_marketing.models.Post.get_upload_path),
        ),
    ]
