# Generated by Django 2.2 on 2020-01-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_marketing', '0006_auto_20200129_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='confirmation_status',
            field=models.CharField(choices=[('0', 'Accepted'), ('1', 'Rejected')], default='0', max_length=1),
        ),
    ]
