# Generated by Django 2.2 on 2020-01-29 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_marketing', '0007_post_confirmation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_confirmed',
        ),
    ]
