# Generated by Django 2.2 on 2020-09-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20200817_1733'),
        ('content_marketing', '0007_auto_20200611_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='remaining_pwa_notif_customers',
            field=models.ManyToManyField(blank=True, to='users.Customer'),
        ),
    ]
