# Generated by Django 2.2 on 2020-01-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_marketing', '0008_remove_post_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='confirmation_status',
            field=models.CharField(choices=[('0', 'Accepted'), ('1', 'Rejected'), ('2', 'Pending')], default='2', max_length=1),
        ),
    ]
