# Generated by Django 2.2 on 2020-01-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_marketing', '0009_auto_20200129_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='confirmation_status',
            field=models.CharField(choices=[('0', 'Rejected'), ('1', 'Accepted'), ('2', 'Pending')], default='2', max_length=1),
        ),
    ]
