# Generated by Django 2.2 on 2021-02-13 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_remove_businessman_address'),
        ('content_marketing', '0009_auto_20210213_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewedPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewed_posts', related_query_name='viewed_posts', to='users.Customer')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers_viewed', related_query_name='customers_viewed', to='content_marketing.Post')),
            ],
            options={
                'unique_together': {('customer', 'post')},
            },
        ),
    ]
