# Generated by Django 2.2 on 2021-02-13 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_remove_businessman_address'),
        ('content_marketing', '0010_viewedpost'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('customer', 'post')},
        ),
    ]
