# Generated by Django 2.2 on 2020-01-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_marketing', '0011_post_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_message_sent',
            field=models.BooleanField(default=False),
        ),
    ]
