# Generated by Django 2.2 on 2021-02-13 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_marketing', '0011_auto_20210213_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='modification_date',
        ),
        migrations.AddField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='businessman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='confirmation_status',
            field=models.CharField(choices=[('0', 'REJECTED'), ('1', 'ACCEPTED'), ('2', 'PENDING')], default='2', max_length=1),
        ),
    ]
