# Generated by Django 2.2 on 2020-01-29 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_marketing', '0012_post_video_message_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video_message_sent',
        ),
    ]
