# Generated by Django 2.2 on 2021-02-14 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_marketing', '0013_post_views'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
    ]
