# Generated by Django 2.2 on 2020-02-19 18:20

import content_marketing.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_marketing', '0014_post_mobile_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='customer_notif_message_template',
            field=models.CharField(max_length=260, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='send_notif_pwa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='send_notif_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='mobile_thumbnail',
            field=models.ImageField(max_length=254, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/content/video/', location='/home/pouya795/Desktop/marketpine-backend/../videos/'), upload_to=content_marketing.models.Post.get_upload_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='videofile',
            field=models.FileField(max_length=254, storage=django.core.files.storage.FileSystemStorage(base_url='/content/video/', location='/home/pouya795/Desktop/marketpine-backend/../videos/'), upload_to=content_marketing.models.Post.get_upload_path),
        ),
    ]
