# Generated by Django 2.2 on 2020-02-25 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smspanel', '0025_smsmessage_send_fail_attempts'),
        ('content_marketing', '0017_auto_20200219_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='customer_sms_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smspanel.SMSMessage'),
        ),
    ]
