# Generated by Django 2.2 on 2020-03-01 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_businessman_has_sms_panel'),
        ('content_marketing', '0018_post_customer_sms_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='customer_sms_message',
        ),
        migrations.AddField(
            model_name='post',
            name='notif_sms',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Customer'),
        ),
        migrations.AddField(
            model_name='post',
            name='send_pwa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='send_sms',
            field=models.BooleanField(default=False),
        ),
    ]
