# Generated by Django 2.2 on 2020-03-01 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_marketing', '0019_auto_20200301_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='notif_sms',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smspanel.SMSMessage'),
        ),
    ]
