# Generated by Django 2.2 on 2019-07-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentSMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('is_plain_sms', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=200)),
            ],
        ),
    ]
