# Generated by Django 2.2 on 2019-05-20 18:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190502_2100'),
        ('smspanel', '0002_customersentsms_sentsms'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentsms',
            name='customers',
            field=models.ManyToManyField(to='users.Customer'),
        ),
        migrations.AddField(
            model_name='sentsms',
            name='sent_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 5, 20, 18, 2, 50, 887408, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CustomerSentSMS',
        ),
    ]
