# Generated by Django 2.2 on 2019-05-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smspanel', '0003_auto_20190520_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentsms',
            name='is_plain_sms',
            field=models.BooleanField(default=False),
        ),
    ]
