# Generated by Django 2.2 on 2019-05-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smspanel', '0004_sentsms_is_plain_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentsms',
            name='content',
            field=models.CharField(max_length=300),
        ),
    ]
