# Generated by Django 2.2 on 2019-10-07 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smspanel', '0004_smspanelinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smspanelinfo',
            name='businessman',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
