# Generated by Django 2.2 on 2019-10-07 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smspanel', '0006_auto_20191007_1328'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SMSPanelInfo',
        ),
    ]
