# Generated by Django 2.2 on 2019-10-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smspanel', '0007_delete_smspanelinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentsms',
            name='content',
        ),
        migrations.RemoveField(
            model_name='sentsms',
            name='is_plain_sms',
        ),
        migrations.RemoveField(
            model_name='sentsms',
            name='sent_date',
        ),
        migrations.AddField(
            model_name='sentsms',
            name='message_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
