# Generated by Django 2.2 on 2019-12-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smspanel', '0009_auto_20191205_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentsms',
            name='is_sent_to_all',
        ),
        migrations.AddField(
            model_name='sentsms',
            name='receptor',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
