# Generated by Django 2.2 on 2019-12-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smspanel', '0011_unsentplainsms'),
    ]

    operations = [
        migrations.AddField(
            model_name='unsentplainsms',
            name='resend_start',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
