# Generated by Django 2.2 on 2019-12-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smspanel', '0013_unsentplainsms_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='smstemplate',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='smstemplate',
            name='content',
            field=models.CharField(max_length=160),
        ),
    ]
