# Generated by Django 2.2 on 2019-12-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_businessman_authorized'),
        ('smspanel', '0015_unsenttemplatesms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unsentplainsms',
            name='resend_start',
        ),
        migrations.RemoveField(
            model_name='unsentplainsms',
            name='resend_stop',
        ),
        migrations.RemoveField(
            model_name='unsenttemplatesms',
            name='resend_start',
        ),
        migrations.RemoveField(
            model_name='unsenttemplatesms',
            name='resend_stop',
        ),
        migrations.AddField(
            model_name='unsentplainsms',
            name='customers',
            field=models.ManyToManyField(to='users.Customer'),
        ),
        migrations.AddField(
            model_name='unsenttemplatesms',
            name='customers',
            field=models.ManyToManyField(to='users.Customer'),
        ),
    ]
