# Generated by Django 2.2 on 2020-02-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200125_0749'),
        ('smspanel', '0017_smsmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmessage',
            name='receptors',
            field=models.ManyToManyField(related_name='receptors', to='users.Customer'),
        ),
    ]
