# Generated by Django 2.2 on 2020-02-20 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200125_0749'),
        ('smspanel', '0019_auto_20200219_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsmessage',
            name='receptors',
        ),
        migrations.AlterField(
            model_name='smsmessage',
            name='status',
            field=models.CharField(choices=[('0', 'CANCLE'), ('1', 'PENDING'), ('2', 'DONE'), ('3', 'FAILED')], default='1', max_length=2),
        ),
        migrations.CreateModel(
            name='SMSMessageReceivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('message_id', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Customer')),
                ('sms_message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smspanel.SMSMessage')),
            ],
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='receivers',
            field=models.ManyToManyField(related_name='receivers', through='smspanel.SMSMessageReceivers', to='users.Customer'),
        ),
    ]
