# Generated by Django 2.2 on 2020-02-20 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200125_0749'),
        ('smspanel', '0020_auto_20200219_2249'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='smsmessagereceivers',
            unique_together={('sms_message', 'customer')},
        ),
    ]
