# Generated by Django 2.2 on 2020-02-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smspanel', '0022_auto_20200219_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmessagereceivers',
            name='message_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
