# Generated by Django 2.2 on 2020-02-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smspanel', '0023_auto_20200219_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsmessagereceivers',
            name='message_id',
        ),
        migrations.AlterField(
            model_name='sentsms',
            name='message_id',
            field=models.CharField(max_length=100),
        ),
    ]
