# Generated by Django 2.2 on 2020-02-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smspanel', '0025_smsmessage_send_fail_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmessage',
            name='used_for',
            field=models.CharField(choices=[('0', 'NONE'), ('1', 'FESTIVAL'), ('2', 'CONTENT MARKETING'), ('3', 'INSTAGRAM MARKETING'), ('4', 'WELCOME MESSAGE'), ('5', 'FRIEND INVITATION')], default='0', max_length=2),
        ),
    ]
