# Generated by Django 2.2 on 2020-02-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smspanel', '0026_smsmessage_used_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmessage',
            name='reserved_credit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
