# Generated by Django 2.2 on 2020-04-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smspanel', '0027_smsmessage_reserved_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmessage',
            name='status',
            field=models.CharField(choices=[('0', 'CANCLE'), ('1', 'PENDING'), ('2', 'DONE'), ('3', 'FAILED'), ('4', 'Waiting for credit recharge')], default='1', max_length=2),
        ),
    ]
