# Generated by Django 2.2 on 2021-01-11 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smspanel', '0031_auto_20210111_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentsms',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sentsms',
            name='sms_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_sms', related_query_name='sent_sms', to='smspanel.SMSMessage'),
        ),
        migrations.AddField(
            model_name='sentsms',
            name='status_text',
            field=models.TextField(null=True),
        ),
    ]
