# Generated by Django 2.2 on 2021-01-11 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smspanel', '0032_auto_20210111_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentsms',
            name='businessman',
        ),
    ]
