# Generated by Django 2.2 on 2021-10-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('smspanel', '0033_remove_sentsms_businessman'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmessage',
            name='current_receiver_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='last_receiver_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
