# Generated by Django 2.2 on 2021-10-08 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('groups', '0001_initial'),
        ('smspanel', '0034_auto_20211008_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmessage',
            name='used_for',
            field=models.CharField(
                choices=[('0', 'NONE'), ('1', 'FESTIVAL'), ('2', 'CONTENT MARKETING'), ('3', 'INSTAGRAM MARKETING'),
                         ('4', 'WELCOME MESSAGE'), ('5', 'FRIEND INVITATION'), ('6', 'SEND TO ALL')], default='0',
                max_length=2),
        ),
        migrations.CreateModel(
            name='SMSMessageReceiverGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('group',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_sms_message',
                                   related_query_name='related_sms_message', to='groups.BusinessmanGroups')),
                ('sms_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                                     related_name='related_receiver_group',
                                                     related_query_name='related_receiver_group',
                                                     to='smspanel.SMSMessage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
