# Generated by Django 2.2 on 2020-03-21 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20191026_0626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='modification_date',
        ),
        migrations.RemoveField(
            model_name='device',
            name='register_date',
        ),
        migrations.AddField(
            model_name='device',
            name='create_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='disabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='device',
            name='key',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='businessman',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='device',
            name='imei',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
