# Generated by Django 2.2 on 2020-08-08 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0023_auto_20200808_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOneTimePasswords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('expiration_time', models.DateTimeField()),
                ('code', models.CharField(max_length=20)),
                ('send_attempts', models.IntegerField(default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_time_passwords', related_query_name='one_time_passwords', to='users.Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerLoginTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.TextField()),
                ('user_agent', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_tokens', related_query_name='login_tokens', to='users.Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
