# Generated by Django 2.2 on 2020-09-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_application', '0002_customeronetimepasswords_last_send_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlogintokens',
            name='token',
            field=models.TextField(unique=True),
        ),
    ]
