# Generated by Django 2.2 on 2020-11-17 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_application', '0004_auto_20201117_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerverificationcode',
            old_name='used_for_choices',
            new_name='used_for',
        ),
    ]
