# Generated by Django 2.2 on 2020-11-17 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_application', '0005_auto_20201117_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerUpdatePhoneModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('new_phone', models.CharField(max_length=20)),
                ('verify_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer_application.CustomerVerificationCode')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
