# Generated by Django 2.2 on 2019-10-07 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSPanelInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('api_key', models.TextField(default=django.db.models.deletion.SET_NULL)),
                ('status', models.CharField(choices=[('1', 'ACTIVE_LOGIN'), ('0', 'INACTIVE'), ('2', 'ACTIVE')], default='0', max_length=1)),
                ('minimum_allowed_credit', models.PositiveIntegerField(default=10000)),
                ('credit', models.PositiveIntegerField(default=1000)),
                ('sms_farsi_cost', models.PositiveSmallIntegerField()),
                ('sms_english_cost', models.PositiveSmallIntegerField()),
                ('businessman', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
