# Generated by Django 2.2 on 2019-10-08 19:45

import common.util.custom_validators
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import panelprofile.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panelprofile', '0003_auto_20191007_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Pouya\\Desktop\\programs\\python\\django rest\\marketpine-backend\\..\\uploaded_media'), upload_to='auth-doc', validators=[common.util.custom_validators.pdf_file_validator])),
            ],
        ),
        migrations.CreateModel(
            name='BusinessmanAuthDocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.FileField(max_length=40, null=True, upload_to=panelprofile.models.BusinessmanAuthDocs.get_upload_path)),
                ('national_card', models.ImageField(max_length=20, null=True, upload_to=panelprofile.models.BusinessmanAuthDocs.get_upload_path)),
                ('birth_certificate', models.ImageField(max_length=20, null=True, upload_to=panelprofile.models.BusinessmanAuthDocs.get_upload_path)),
                ('businessman', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
