# Generated by Django 2.2 on 2019-11-17 17:42

import common.util.custom_validators
import django.core.files.storage
from django.db import migrations, models
import panelprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('panelprofile', '0005_auto_20191009_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authdoc',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Pouya\\Desktop\\programs\\python\\marketpine-backend\\..\\uploaded_media'), upload_to='auth-doc', validators=[common.util.custom_validators.pdf_file_validator]),
        ),
        migrations.AlterField(
            model_name='businessmanauthdocs',
            name='birth_certificate',
            field=models.ImageField(max_length=80, null=True, upload_to=panelprofile.models.BusinessmanAuthDocs.get_upload_path),
        ),
        migrations.AlterField(
            model_name='businessmanauthdocs',
            name='form',
            field=models.FileField(max_length=80, null=True, upload_to=panelprofile.models.BusinessmanAuthDocs.get_upload_path),
        ),
        migrations.AlterField(
            model_name='businessmanauthdocs',
            name='national_card',
            field=models.ImageField(max_length=80, null=True, upload_to=panelprofile.models.BusinessmanAuthDocs.get_upload_path),
        ),
    ]
