# Generated by Django 2.2 on 2020-01-28 18:12

import common.util.custom_validators
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelprofile', '0009_auto_20191221_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authdoc',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Pouya\\Desktop\\programs\\python\\marketpine-backend\\..\\uploaded_media/'), upload_to='auth-doc', validators=[common.util.custom_validators.pdf_file_validator]),
        ),
    ]
