# Generated by Django 2.2 on 2020-06-11 16:48

import base_app.models
import common.util.custom_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelprofile', '0015_auto_20200502_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authdoc',
            name='file',
            field=models.FileField(storage=base_app.models.PublicFileStorage('commit_form/', '/commit-form/'), upload_to='auth-doc', validators=[common.util.custom_validators.pdf_file_validator]),
        ),
    ]
