# Generated by Django 2.2 on 2020-11-08 12:05

from django.db import migrations, models
import panelprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('panelprofile', '0016_auto_20200611_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmanauthdocs',
            name='birth_certificate',
            field=models.ImageField(max_length=300, null=True, upload_to=panelprofile.models.BusinessmanAuthDocs.get_upload_path),
        ),
        migrations.AlterField(
            model_name='businessmanauthdocs',
            name='form',
            field=models.FileField(max_length=300, null=True, upload_to=panelprofile.models.BusinessmanAuthDocs.get_upload_path),
        ),
        migrations.AlterField(
            model_name='businessmanauthdocs',
            name='national_card',
            field=models.ImageField(max_length=300, null=True, upload_to=panelprofile.models.BusinessmanAuthDocs.get_upload_path),
        ),
    ]
