# Generated by Django 2.2 on 2020-12-12 14:34

import base_app.models
from django.db import migrations, models
import panelprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('panelprofile', '0017_auto_20201108_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmanauthdocs',
            name='birth_certificate',
            field=models.ImageField(max_length=300, null=True, storage=base_app.models.PrivateFileStorage('auth-docs/', '/auth-docs/'), upload_to=panelprofile.models.BusinessmanAuthDocs.get_upload_path),
        ),
        migrations.AlterField(
            model_name='businessmanauthdocs',
            name='form',
            field=models.FileField(max_length=300, null=True, storage=base_app.models.PrivateFileStorage('auth-docs/', '/auth-docs/'), upload_to=panelprofile.models.BusinessmanAuthDocs.get_upload_path),
        ),
        migrations.AlterField(
            model_name='businessmanauthdocs',
            name='national_card',
            field=models.ImageField(max_length=300, null=True, storage=base_app.models.PrivateFileStorage('auth-docs/', '/auth-docs/'), upload_to=panelprofile.models.BusinessmanAuthDocs.get_upload_path),
        ),
    ]
