# Generated by Django 2.2 on 2021-05-17 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panelprofile', '0019_auto_20201212_1817'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthDoc',
        ),
    ]
