# Generated by Django 2.2 on 2021-05-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelprofile', '0020_delete_authdoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smspanelinfo',
            name='status',
            field=models.CharField(choices=[('ApprovedWithoutLogin', 'ACTIVE_LOGIN'), ('Disabled', 'INACTIVE'), ('ApprovedWithoutLogin', 'ACTIVE')], default='0', max_length=20),
        ),
    ]
