# Generated by Django 2.2 on 2021-05-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelprofile', '0021_auto_20210518_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smspanelinfo',
            name='status',
            field=models.CharField(choices=[('Approved', 'ACTIVE_LOGIN'), ('Disabled', 'INACTIVE'), ('ApprovedWithoutLogin', 'ACTIVE')], default='0', max_length=20),
        ),
    ]
