# Generated by Django 2.2 on 2019-08-03 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessmanModulus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('expire_at', models.DateTimeField()),
                ('businessman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Businessman Modulus',
                'db_table': 'businessman_modulus',
            },
        ),
        migrations.CreateModel(
            name='PanelModulus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cost', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('businessman', models.ManyToManyField(through='panelmodulus.BusinessmanModulus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Panel Modulus',
                'db_table': 'panel_modulus',
            },
        ),
        migrations.AddField(
            model_name='businessmanmodulus',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panelmodulus.PanelModulus'),
        ),
    ]
