# Generated by Django 2.2 on 2020-04-24 18:05

import django.core.files.storage
from django.db import migrations, models
import online_menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('online_menu', '0002_auto_20200422_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinemenu',
            name='file',
            field=models.ImageField(max_length=200, storage=django.core.files.storage.FileSystemStorage(base_url='/menu/', location='/home/pouya795/Desktop/marketpine-backend/../public/menus/'), upload_to=online_menu.models.OnlineMenu.get_upload_path),
        ),
    ]
