# Generated by Django 2.2 on 2020-06-11 16:02

import base_app.models
from django.db import migrations, models
import online_menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('online_menu', '0003_auto_20200502_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinemenu',
            name='file',
            field=models.ImageField(max_length=200, storage=base_app.models.PublicFileStorage('menus/', base_url='/menu/'), upload_to=online_menu.models.OnlineMenu.get_upload_path),
        ),
    ]
