# Generated by Django 2.2 on 2020-09-28 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_menu', '0004_auto_20200611_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlinemenu',
            old_name='file',
            new_name='image',
        ),
        migrations.AddField(
            model_name='onlinemenu',
            name='show_order',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='onlinemenu',
            name='businessman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
