# Generated by Django 2.2 on 2020-09-28 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_menu', '0005_auto_20200928_0911'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='onlinemenu',
            unique_together={('id', 'show_order')},
        ),
    ]
