# Generated by Django 2.2 on 2020-09-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_menu', '0006_auto_20200928_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinemenu',
            name='show_order',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='onlinemenu',
            unique_together=set(),
        ),
    ]
