# Generated by Django 2.2 on 2020-09-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_menu', '0007_auto_20200928_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinemenu',
            name='show_order',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
