# Generated by Django 2.2 on 2020-06-06 20:02

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import users.util


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileAppPageConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('store_location', models.TextField(null=True)),
                ('businessman', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MobileAppHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('header_image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/mobile-app/', location='/home/pouya/projects/python/marketpine-backend/../public/mobile_app/'), upload_to=users.util.businessman_related_model_file_upload_path)),
                ('mobile_app_page_conf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headers', related_query_name='headers', to='mobile_app_conf.MobileAppPageConf')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
