# Generated by Django 2.2 on 2020-06-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app_conf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileapppageconf',
            name='store_location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
