# Generated by Django 2.2 on 2020-06-06 20:14

import django.core.files.storage
from django.db import migrations, models
import mobile_app_conf.models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app_conf', '0002_auto_20200606_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileappheader',
            name='header_image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/mobile-app/', location='/home/pouya/projects/python/marketpine-backend/../public/mobile_app/'), upload_to=mobile_app_conf.models.mobile_app_header_upload_path),
        ),
    ]
