# Generated by Django 2.2 on 2020-06-11 16:10

import base_app.models
from django.db import migrations, models
import mobile_app_conf.models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app_conf', '0004_auto_20200609_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileappheader',
            name='header_image',
            field=models.ImageField(storage=base_app.models.PublicFileStorage(base_url='/mobile-app/', subdir='mobile_app/'), upload_to=mobile_app_conf.models.mobile_app_header_upload_path),
        ),
    ]
