# Generated by Django 2.2 on 2020-07-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app_conf', '0005_auto_20200611_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileappheader',
            name='header_image_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
