# Generated by Django 2.2 on 2020-07-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app_conf', '0006_mobileappheader_header_image_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobileapppageconf',
            name='market_location',
        ),
        migrations.AddField(
            model_name='mobileapppageconf',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='mobileapppageconf',
            name='is_location_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mobileapppageconf',
            name='location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobileapppageconf',
            name='location_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
