# Generated by Django 2.2 on 2021-01-08 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app_conf', '0008_mobileapppageconf_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('mobile_app_page_conf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', related_query_name='contact_info', to='mobile_app_conf.MobileAppPageConf')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
