# Generated by Django 2.2 on 2021-04-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app_conf', '0009_contactinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileapppageconf',
            name='page_id',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
