# Generated by Django 2.2 on 2021-04-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app_conf', '0010_mobileapppageconf_page_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileapppageconf',
            name='instagram_page_url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
