# Generated by Django 2.2 on 2021-04-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app_conf', '0011_mobileapppageconf_instagram_page_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileapppageconf',
            name='working_time_from',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
