# Generated by Django 2.2 on 2021-04-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app_conf', '0012_mobileapppageconf_working_time_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileapppageconf',
            name='working_time_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
