# Generated by Django 2.2 on 2021-04-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app_conf', '0013_mobileapppageconf_working_time_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileapppageconf',
            name='telegram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobileapppageconf',
            name='instagram_page_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
