# Generated by Django 2.2 on 2021-04-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app_conf', '0014_auto_20210427_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileapppageconf',
            name='show_working_time',
            field=models.BooleanField(default=False),
        ),
    ]
