# Generated by Django 2.2 on 2019-08-04 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panelsetting', '0002_auto_20190804_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelsetting',
            name='businessman',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='panelsetting',
            name='welcome_message',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
