# Generated by Django 2.2 on 2020-04-22 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panelsetting', '0003_auto_20190804_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelsetting',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='panelsetting',
            name='send_welcome_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='panelsetting',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='panelsetting',
            name='businessman',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
