# Generated by Django 2.2 on 2019-05-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190502_2100'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessmangroups',
            name='customer',
        ),
        migrations.AddField(
            model_name='businessmangroups',
            name='customers',
            field=models.ManyToManyField(to='users.Customer'),
        ),
    ]
