# Generated by Django 2.2 on 2020-05-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20200502_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmangroups',
            name='type',
            field=models.CharField(choices=[('0', 'NORMAL'), ('1', 'TOP_PURCHASE')], default='0', max_length=2),
        ),
    ]
