# Generated by Django 2.2 on 2020-10-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20200515_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmangroups',
            name='customers',
            field=models.ManyToManyField(related_name='connected_groups', related_query_name='connected_groups', to='users.Customer'),
        ),
    ]
