# Generated by Django 2.2 on 2020-10-11 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_customer_is_phone_confirmed'),
        ('groups', '0005_auto_20201011_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='group_customer', to='users.Customer')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='group_customer', to='groups.BusinessmanGroups')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
