# Generated by Django 2.2 on 2020-10-11 09:33
import datetime

from django.db import migrations

def create_through_relations(apps, schema_editor):
    Group = apps.get_model('groups', 'BusinessmanGroups')
    Membership = apps.get_model('groups', 'Membership')
    for group in Group.objects.all():
        for member in group.customers.all():
            Membership(
                customer=member,
                group=group,
                create_date=datetime.date.today()
            ).save()


class Migration(migrations.Migration):


    dependencies = [
        ('groups', '0006_groupcustomer'),
    ]

    operations = [
        migrations.RunPython(create_through_relations, reverse_code=migrations.RunPython.noop)
    ]
