# Generated by Django 2.2 on 2020-10-11 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_auto_20201011_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessmangroups',
            name='customers',
        ),
    ]
