# Generated by Django 2.2 on 2020-10-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_customer_is_phone_confirmed'),
        ('groups', '0008_remove_businessmangroups_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmangroups',
            name='customers',
            field=models.ManyToManyField(related_name='connected_groups', related_query_name='connected_groups', through='groups.GroupCustomer', to='users.Customer'),
        ),
    ]
