# Generated by Django 2.2 on 2020-10-11 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_customer_is_phone_confirmed'),
        ('groups', '0009_businessmangroups_customers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupCustomer',
            new_name='Membership',
        ),
    ]
