# Generated by Django 2.2 on 2020-03-17 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invitation', '0004_friendinvitationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendinvitationsettings',
            name='businessman',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='friendinvitationsettings',
            name='discount_type',
            field=models.CharField(choices=[('Percent', '0'), ('Flat rate', '1')], default='0', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='friendinvitationsettings',
            name='sms_template',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
