# Generated by Django 2.2 on 2020-03-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0008_friendinvitation_sms_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendinvitation',
            name='discount_type',
            field=models.CharField(choices=[('0', 'Percent'), ('1', 'Flat rate')], default='0', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='friendinvitation',
            name='flat_rate_off',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='friendinvitation',
            name='percent_off',
            field=models.FloatField(default=0),
        ),
    ]
