# Generated by Django 2.2 on 2020-03-19 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0010_auto_20200319_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendinvitation',
            name='sms_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smspanel.SMSMessage'),
        ),
    ]
