# Generated by Django 2.2 on 2020-03-24 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_return_plan', '0001_initial'),
        ('invitation', '0011_auto_20200319_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendinvitation',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='friendinvitation',
            name='flat_rate_off',
        ),
        migrations.RemoveField(
            model_name='friendinvitation',
            name='invitation_date',
        ),
        migrations.RemoveField(
            model_name='friendinvitation',
            name='invited_discount_code',
        ),
        migrations.RemoveField(
            model_name='friendinvitation',
            name='inviter_discount_code',
        ),
        migrations.RemoveField(
            model_name='friendinvitation',
            name='percent_off',
        ),
        migrations.AddField(
            model_name='friendinvitation',
            name='create_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='friendinvitation',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='customer_return_plan.Discount'),
        ),
        migrations.AddField(
            model_name='friendinvitation',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='friendinvitation',
            name='businessman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='FriendInvitationDiscount',
        ),
    ]
