# Generated by Django 2.2 on 2020-03-24 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_businessman_has_sms_panel'),
        ('invitation', '0012_auto_20200324_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendinvitation',
            name='customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to='users.Customer'),
        ),
        migrations.AddField(
            model_name='friendinvitation',
            name='invitation_type',
            field=models.CharField(choices=[('0', 'Invited'), ('1', 'inviter')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='friendinvitation',
            name='discount',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='customer_return_plan.Discount'),
        ),
        migrations.AlterUniqueTogether(
            name='friendinvitation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='friendinvitation',
            name='invited',
        ),
        migrations.RemoveField(
            model_name='friendinvitation',
            name='inviter',
        ),
    ]
