# Generated by Django 2.2 on 2020-03-24 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0013_auto_20200324_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendinvitation',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to='users.Customer'),
        ),
    ]
