# Generated by Django 2.2 on 2020-03-25 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_return_plan', '0003_auto_20200325_1843'),
        ('invitation', '0015_auto_20200325_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendinvitation',
            name='discount',
        ),
        migrations.AddField(
            model_name='friendinvitation',
            name='invited_discount',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invited_discount', to='customer_return_plan.Discount'),
        ),
        migrations.AddField(
            model_name='friendinvitation',
            name='inviter_discount',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inviter_discount', to='customer_return_plan.Discount'),
        ),
    ]
