# Generated by Django 2.2 on 2020-03-25 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0016_auto_20200325_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendinvitation',
            name='invited',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited', to='users.Customer'),
        ),
    ]
