# Generated by Django 2.2 on 2021-06-15 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('invitation', '0021_auto_20200415_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendinvitation',
            name='invited',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited',
                                    to='users.BusinessmanCustomer'),
        ),
        migrations.AlterField(
            model_name='friendinvitation',
            name='inviter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inviter',
                                    to='users.BusinessmanCustomer'),
        ),
    ]
