# Generated by Django 2.2 on 2019-07-28 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerpurchase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerpurchase',
            old_name='purchase_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='customerpurchase',
            old_name='purchase_date',
            new_name='date',
        ),
    ]
