# Generated by Django 2.2 on 2019-08-01 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerpurchase', '0002_auto_20190730_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerpurchase',
            old_name='date',
            new_name='purchase_date',
        ),
    ]
