# Generated by Django 2.2 on 2019-07-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerpurchase', '0002_auto_20190728_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpurchase',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
