# Generated by Django 2.2 on 2020-04-03 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customerpurchase', '0003_auto_20190801_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerpurchase',
            name='purchase_date',
        ),
        migrations.AddField(
            model_name='customerpurchase',
            name='create_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='customerpurchase',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerpurchase',
            name='businessman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
