# Generated by Django 2.2 on 2020-04-13 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0007_auto_20200413_2050'),
        ('customerpurchase', '0005_auto_20200412_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpurchase',
            name='loyalty_setting',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='loyalty.CustomerLoyaltyDiscountSettings'),
        ),
    ]
