# Generated by Django 2.2 on 2020-04-13 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customerpurchase', '0006_customerpurchase_loyalty_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpurchase',
            name='loyalty_setting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='loyalty.CustomerLoyaltyDiscountSettings'),
        ),
    ]
