# Generated by Django 2.2 on 2020-04-13 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customerpurchase', '0007_auto_20200413_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpurchase',
            name='loyalty_setting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', related_query_name='purchases', to='loyalty.CustomerLoyaltyDiscountSettings'),
        ),
    ]
