# Generated by Django 2.2 on 2020-04-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpurchaseamountdiscountsettings',
            name='purchase_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customerpurchasenumberdiscountsettings',
            name='purchase_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
