# Generated by Django 2.2 on 2020-04-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_auto_20200410_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpurchaseamountdiscountsettings',
            name='purchase_amount',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='customerpurchasenumberdiscountsettings',
            name='purchase_number',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
