# Generated by Django 2.2 on 2020-04-13 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0006_auto_20200412_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerloyaltydiscountsettings',
            name='businessman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
