# Generated by Django 2.2 on 2020-04-13 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0007_auto_20200413_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerpurchaseamountdiscountsettings',
            name='purchase_amount',
        ),
        migrations.CreateModel(
            name='PurchaseAmountPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_from', models.PositiveIntegerField()),
                ('amount_to', models.PositiveIntegerField()),
                ('amount_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', related_query_name='periods', to='loyalty.CustomerPurchaseAmountDiscountSettings')),
            ],
        ),
    ]
