# Generated by Django 2.2 on 2020-04-13 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0008_auto_20200413_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpurchaseamountdiscountsettings',
            name='amount_from',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customerpurchaseamountdiscountsettings',
            name='amount_to',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customerloyaltydiscountsettings',
            name='purchase_amount_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyalty.CustomerPurchaseAmountDiscountSettings'),
        ),
        migrations.DeleteModel(
            name='PurchaseAmountPeriod',
        ),
    ]
