# Generated by Django 2.2 on 2020-04-13 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0009_auto_20200413_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOneTimePurchaseAmountDiscountSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('discount_type', models.CharField(choices=[('0', 'Percent'), ('1', 'Flat rate')], default='0', max_length=2, null=True)),
                ('percent_off', models.FloatField(default=0)),
                ('flat_rate_off', models.PositiveIntegerField(default=0)),
                ('purchase_amount', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerSumPurchaseAmountDiscountSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('discount_type', models.CharField(choices=[('0', 'Percent'), ('1', 'Flat rate')], default='0', max_length=2, null=True)),
                ('percent_off', models.FloatField(default=0)),
                ('flat_rate_off', models.PositiveIntegerField(default=0)),
                ('purchase_amount_sum', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='customerloyaltydiscountsettings',
            name='purchase_amount_settings',
        ),
        migrations.AlterField(
            model_name='customerloyaltydiscountsettings',
            name='purchase_number_settings',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='loyalty.CustomerPurchaseNumberDiscountSettings'),
        ),
        migrations.DeleteModel(
            name='CustomerPurchaseAmountDiscountSettings',
        ),
        migrations.AddField(
            model_name='customerloyaltydiscountsettings',
            name='one_time_purchase_amount_settings',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='loyalty.CustomerOneTimePurchaseAmountDiscountSettings'),
        ),
        migrations.AddField(
            model_name='customerloyaltydiscountsettings',
            name='sum_purchase_amount_setting',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='loyalty.CustomerSumPurchaseAmountDiscountSettings'),
        ),
    ]
