# Generated by Django 2.2 on 2021-07-22 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loyalty', '0013_auto_20200415_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerloyaltydiscountsettings',
            name='discount_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customerloyaltydiscountsettings',
            name='discount_type',
            field=models.CharField(choices=[('0', 'Percent'), ('1', 'Flat rate')], default='0', max_length=2,
                                   null=True),
        ),
        migrations.AddField(
            model_name='customerloyaltydiscountsettings',
            name='flat_rate_off',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customerloyaltydiscountsettings',
            name='percent_off',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customerloyaltydiscountsettings',
            name='point',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customerloyaltydiscountsettings',
            name='businessman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='customerloyaltydiscountsettings',
            unique_together={('businessman', 'point')},
        ),
        migrations.AlterModelTable(
            name='customerloyaltydiscountsettings',
            table='loyalty_settings',
        ),
        migrations.RemoveField(
            model_name='customerloyaltydiscountsettings',
            name='create_discount_for',
        ),
        migrations.RemoveField(
            model_name='customerloyaltydiscountsettings',
            name='disabled',
        ),
        migrations.RemoveField(
            model_name='customerloyaltydiscountsettings',
            name='purchase_amount_settings',
        ),
        migrations.RemoveField(
            model_name='customerloyaltydiscountsettings',
            name='purchase_number_settings',
        ),
    ]
