# Generated by Django 2.2 on 2021-07-22 19:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('loyalty', '0014_auto_20210722_1910'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customerloyaltydiscountsettings',
            unique_together=set(),
        ),
    ]
