# Generated by Django 2.2 on 2021-07-24 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('customer_return_plan', '0015_auto_20200601_1646'),
        ('users', '0040_auto_20210620_1957'),
        ('loyalty', '0016_customerpoints'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerpoints',
            options={'verbose_name': 'Customer points', 'verbose_name_plural': 'Customer points'},
        ),
        migrations.CreateModel(
            name='CustomerExclusiveDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('customer',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exclusive_discounts',
                                   related_query_name='exclusive_discounts', to='users.Customer')),
                ('discount',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exclusive_customers',
                                   related_query_name='exclusive_customers', to='customer_return_plan.Discount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
