# Generated by Django 2.2 on 2021-07-24 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loyalty', '0018_auto_20210724_1433'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customerloyaltydiscountsettings',
            table='loyalty_discount_settings',
        ),
        migrations.CreateModel(
            name='CustomerLoyaltySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('businessman',
                 models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loyalty_settings',
            },
        ),
    ]
