# Generated by Django 2.2 on 2021-10-08 12:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('loyalty', '0020_auto_20210724_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerloyaltydiscountsettings',
            options={'ordering': ['point']},
        ),
    ]
