# Generated by Django 2.2 on 2020-04-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('local_id', models.PositiveIntegerField()),
                ('pid', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('0', 'RUNNING'), ('1', 'KILL')], default='1', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
