# Generated by Django 2.2 on 2020-09-26 07:08

import base_app.models
from django.db import migrations, models
import django.db.models.deletion
import educations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('video', models.FileField(storage=base_app.models.PublicFileStorage(base_url='/educations/', subdir='educations/'), upload_to=educations.models.Education.get_upload_path)),
                ('image', models.ImageField(storage=base_app.models.PublicFileStorage(base_url='/educations/', subdir='educations/'), upload_to=educations.models.Education.get_upload_path)),
                ('title', models.CharField(max_length=100)),
                ('education_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='educations.EducationType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
