# Generated by Django 2.2 on 2019-07-26 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0008_auto_20190719_0102'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_date', models.DateField(auto_now_add=True)),
                ('invitor_discount_code', models.CharField(max_length=9)),
                ('invited_discount_code', models.CharField(max_length=9)),
                ('invitor_discount_used', models.BooleanField(default=False)),
                ('invited_discount_used', models.BooleanField(default=False)),
                ('new', models.BooleanField(default=True)),
                ('businessman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('invited', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Customer')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_friends', to='users.Customer')),
            ],
            options={
                'db_table': 'friend_invitation',
                'unique_together': {('businessman', 'invited'), ('businessman', 'invited_by', 'invitor_discount_code')},
            },
        ),
    ]
