# Generated by Django 2.2 on 2019-07-17 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_phone', models.CharField(max_length=15)),
                ('invitation_date', models.DateField()),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Customer')),
            ],
            options={
                'db_table': 'friend_invitation',
                'unique_together': {('invited_by', 'friend_phone')},
            },
        ),
    ]
