# Generated by Django 2.2 on 2019-07-28 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('invitation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendinvitationdiscount',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Customer'),
        ),
        migrations.AddField(
            model_name='friendinvitationdiscount',
            name='friend_invitation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invitation.FriendInvitation'),
        ),
        migrations.AddField(
            model_name='friendinvitation',
            name='businessman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friendinvitation',
            name='invited',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Customer'),
        ),
        migrations.AddField(
            model_name='friendinvitation',
            name='inviter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_friends', to='users.Customer'),
        ),
        migrations.AlterUniqueTogether(
            name='friendinvitationdiscount',
            unique_together={('friend_invitation', 'customer')},
        ),
        migrations.AlterUniqueTogether(
            name='friendinvitation',
            unique_together={('businessman', 'invited')},
        ),
    ]
