# Generated by Django 2.2 on 2019-07-26 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_auto_20190719_0102'),
        ('invitation', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendinvitation',
            unique_together={('businessman', 'invited')},
        ),
        migrations.CreateModel(
            name='InvitedFriendDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_code', models.CharField(max_length=9)),
                ('friend_invitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='invitation.FriendInvitation')),
            ],
            options={
                'db_table': 'friend_invited_discount',
            },
        ),
        migrations.CreateModel(
            name='FriendInvitorDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_code', models.CharField(max_length=9)),
                ('friend_invitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='invitation.FriendInvitation')),
            ],
            options={
                'db_table': 'friend_invitor_discount',
            },
        ),
        migrations.RemoveField(
            model_name='friendinvitation',
            name='invited_discount_code',
        ),
        migrations.RemoveField(
            model_name='friendinvitation',
            name='invited_discount_used',
        ),
        migrations.RemoveField(
            model_name='friendinvitation',
            name='invitor_discount_code',
        ),
        migrations.RemoveField(
            model_name='friendinvitation',
            name='invitor_discount_used',
        ),
    ]
