# Generated by Django 2.2 on 2019-07-17 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invitation', '0002_auto_20190717_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendinvitation',
            name='businessman',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='friendinvitation',
            unique_together={('businessman', 'friend_phone')},
        ),
    ]
