# Generated by Django 2.2 on 2020-03-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0002_auto_20190730_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendinvitationdiscount',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
