# Generated by Django 2.2 on 2019-07-26 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0002_auto_20190726_1506'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FriendInvitorDiscount',
            new_name='FriendInviterDiscount',
        ),
        migrations.RenameField(
            model_name='friendinvitation',
            old_name='invited_by',
            new_name='inviter',
        ),
    ]
