# Generated by Django 2.2 on 2019-07-26 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190719_0102'),
        ('invitation', '0003_auto_20190726_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendinviterdiscount',
            name='inviter',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='users.Customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitedfrienddiscount',
            name='invited',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='users.Customer'),
            preserve_default=False,
        ),
    ]
