# Generated by Django 2.2 on 2019-07-26 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0004_auto_20190726_1702'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='friendinviterdiscount',
            table='friend_inviter_discount',
        ),
    ]
