# Generated by Django 2.2 on 2020-03-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0005_auto_20200317_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendinvitationdiscount',
            name='discount_type',
            field=models.CharField(choices=[('0', 'Percent'), ('1', 'Flat rate')], default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='friendinvitationdiscount',
            name='flat_rate_off',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='friendinvitationdiscount',
            name='percent_off',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='friendinvitationsettings',
            name='discount_type',
            field=models.CharField(choices=[('0', 'Percent'), ('1', 'Flat rate')], default='0', max_length=2, null=True),
        ),
    ]
