# Generated by Django 2.2 on 2019-07-27 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190728_0246'),
        ('invitation', '0005_auto_20190726_1829'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendinviterdiscount',
            unique_together={('inviter', 'friend_invitation')},
        ),
        migrations.AlterUniqueTogether(
            name='invitedfrienddiscount',
            unique_together={('invited', 'friend_invitation')},
        ),
    ]
