# Generated by Django 2.2 on 2019-07-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0005_auto_20190717_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendinvitation',
            name='new',
            field=models.BooleanField(default=False),
        ),
    ]
