# Generated by Django 2.2 on 2019-07-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0006_friendinvitation_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendinvitation',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
