# Generated by Django 2.2 on 2019-07-28 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190728_0246'),
        ('invitation', '0006_auto_20190728_0246'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendInvitationDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_code', models.CharField(max_length=9)),
                ('role', models.CharField(choices=[('IR', 'Inviter'), ('ID', 'Invited')], max_length=2)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Customer')),
                ('friend_invitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='invitation.FriendInvitation')),
            ],
            options={
                'db_table': 'friend_invitation_discount',
            },
        ),
        migrations.AlterUniqueTogether(
            name='invitedfrienddiscount',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='invitedfrienddiscount',
            name='friend_invitation',
        ),
        migrations.RemoveField(
            model_name='invitedfrienddiscount',
            name='invited',
        ),
        migrations.DeleteModel(
            name='FriendInviterDiscount',
        ),
        migrations.DeleteModel(
            name='InvitedFriendDiscount',
        ),
    ]
