# Generated by Django 2.2 on 2020-03-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0006_auto_20200317_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendinvitationdiscount',
            name='discount_type',
            field=models.CharField(choices=[('0', 'Percent'), ('1', 'Flat rate')], default='0', max_length=2, null=True),
        ),
    ]
