# Generated by Django 2.2 on 2019-07-28 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190728_0246'),
        ('invitation', '0007_auto_20190728_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendinvitationdiscount',
            name='friend_invitation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invitation.FriendInvitation'),
        ),
        migrations.AlterUniqueTogether(
            name='friendinvitationdiscount',
            unique_together={('friend_invitation', 'customer')},
        ),
    ]
