# Generated by Django 2.2 on 2020-03-19 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smspanel', '0027_smsmessage_reserved_credit'),
        ('invitation', '0007_auto_20200317_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendinvitation',
            name='sms_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smspanel.SMSMessage'),
        ),
    ]
