# Generated by Django 2.2 on 2020-03-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0009_auto_20200319_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendinvitation',
            name='invited_discount_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='friendinvitation',
            name='inviter_discount_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
