# Generated by Django 2.2 on 2019-07-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='discount_code',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
