# Generated by Django 2.2 on 2019-07-31 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0002_auto_20190730_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='message',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
