# Generated by Django 2.2 on 2019-07-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0002_auto_20190715_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='is_general',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='festival',
            name='percent_off',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
