# Generated by Django 2.2 on 2019-07-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0003_auto_20190715_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='discount_code',
            field=models.CharField(max_length=12),
        ),
    ]
