# Generated by Django 2.2 on 2019-07-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0004_auto_20190715_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
