# Generated by Django 2.2 on 2019-07-15 19:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('festivals', '0006_auto_20190715_1744'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='festival',
            unique_together={('businessman', 'discount_code'), ('businessman', 'name')},
        ),
    ]
