# Generated by Django 2.2 on 2020-03-08 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smspanel', '0027_smsmessage_reserved_credit'),
        ('festivals', '0006_festival_messages_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festival',
            name='message',
        ),
        migrations.RemoveField(
            model_name='festival',
            name='messages_sent',
        ),
        migrations.AddField(
            model_name='festival',
            name='sms_message',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='smspanel.SMSMessage'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
