# Generated by Django 2.2 on 2020-03-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0007_auto_20200308_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='message_sent',
            field=models.BooleanField(default=False),
        ),
    ]
