# Generated by Django 2.2 on 2019-07-15 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('festivals', '0007_auto_20190716_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFestival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Customer')),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festivals.Festival')),
            ],
            options={
                'unique_together': {('customer', 'festival')},
            },
        ),
    ]
