# Generated by Django 2.2 on 2019-07-15 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0008_customerfestival'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerFestival',
        ),
    ]
