# Generated by Django 2.2 on 2019-07-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('festivals', '0009_delete_customerfestival'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='customers',
            field=models.ManyToManyField(to='users.Customer'),
        ),
    ]
