# Generated by Django 2.2 on 2019-07-28 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0010_festival_customers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festival',
            name='is_general',
        ),
    ]
